eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


server:
  port: 8062
spring:
  application:
    name: comsumer



